name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ubuntu
          EC2_IP: 44.211.169.22
        run: |
          scp -i ec2-key.pem -o StrictHostKeyChecking=no -r . $EC2_USER@$EC2_IP:/home/ubuntu/BlockHouse-Take-Home

          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            cd /home/ubuntu/BlockHouse-Take-Home
            docker build -t trade-app .
            docker run -d -p 8000:8000 trade-app
          EOF

      - name: Checkout code
        uses: actions/checkout@v2
